using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Reflection;
using System.IO;
using Deltin.Deltinteger.Elements;

namespace Deltin.Deltinteger
{
    public static class Constants
    {
        public static readonly string WorkingDirectory = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);

        public const int RULE_NAME_MAX_LENGTH = 128;

        public const double MINIMUM_WAIT = 0.016;

        public const string INTERNAL_ELEMENT = "INTERNAL : ";

        public const string DEFAULT_STRING = "hello";

        // All credit to https://us.forums.blizzard.com/en/overwatch/t/workshop-resource-get-the-current-map-name-updated-1-action/
        public static readonly int[][] MapChecks = new int[][]
        {
            new int[]
            {
                1416,
                2318,
                7037,
                2369,
                4693,
                4013,
                1514,
                3111,
                2146,
                2226,
                1671,
                1430,
                4143,
                553,
                1228,
                4524,
                992,
                4445,
                3091,
                6182,
                901,
                1414,
                2794,
                2432
            },
            new int[]
            {
                2729,
                2308,
                2823,
                1635,
                2853,
                6694,
                7722,
                4244,
                9362,
                4686,
                1717,
                4831,
                2016,
                5017,
                6014,
                4165,
                40,
                41,
                42,
                43,
                44,
                45,
                46,
                47
            }
        };

        public static readonly string[] Strings = new string[]
        {
            // All lowercase please :)
            "",
            "----------",
            "-> {0}",
            "!",
            "!!",
            "!!!",
            "#{0}",
            "({0})",
            "*",
            "...",
            "?",
            "??",
            "???",
            "{0} - {1}",
            "{0} - {1} - {2}",
            "{0} ->",
            "{0} -> {1}",
            "{0} != {1}",
            "{0} * {1}",
            "{0} / {1}",
            "{0} : {1} : {2}",
            "{0} {1}",
            "{0} {1} {2}",
            "{0} + {1}",
            "{0} <-",
            "{0} <- {1}",
            "{0} <->",
            "{0} <-> {1}",
            "{0} < {1}",
            "{0} <= {1}",
            "{0} = {1}",
            "{0} == {1}",
            "{0} > {1}",
            "{0} >= {1}",
            "{0} and {1}",
            "{0} m",
            "{0} m/s",
            "{0} sec",
            "{0} vs {1}",
            "{0}!",
            "{0}!!",
            "{0}!!!",
            "{0}%",
            "{0}, {1}",
            "{0}, {1}, and {2}",
            "{0}:",
            "{0}: {1}",
            "{0}: {1} and {2}",
            "{0}:{1}",
            "{0}?",
            "{0}??",
            "{0}???",
            "<- {0}",
            "<-> {0}",
            "abilities",
            "ability",
            "ability 1",
            "ability 2",
            "alert",
            "alive",
            "allies",
            "ally",
            "ammunition",
            "angle",
            "attack",
            "attacked",
            "attacking",
            "attempt",
            "attempts",
            "average",
            "avoid",
            "avoided",
            "avoiding",
            "backward",
            "bad",
            "ban",
            "banned",
            "banning",
            "best",
            "better",
            "bid",
            "bids",
            "block",
            "blocked",
            "blocking",
            "blue",
            "bonus",
            "bonuses",
            "boss",
            "bosses",
            "bought",
            "build",
            "building",
            "built",
            "burn",
            "burning",
            "burnt",
            "buy",
            "buying",
            "capture",
            "captured",
            "capturing",
            "caution",
            "center",
            "challenge accepted",
            "charisma",
            "chase",
            "chased",
            "chasing",
            "checkpoint",
            "checkpoints",
            "cloud",
            "clouds",
            "club",
            "clubs",
            "combo",
            "come here",
            "condition",
            "congratulations",
            "connect",
            "connected",
            "connecting",
            "constitution",
            "control point",
            "control points",
            "cooldown",
            "cooldowns",
            "corrupt",
            "corrupted",
            "corrupting",
            "credit",
            "credits",
            "critical",
            "crouch",
            "crouched",
            "crouching",
            "current",
            "current allies",
            "current ally",
            "current attempt",
            "current checkpoint",
            "current enemies",
            "current enemy",
            "current form",
            "current game",
            "current hero",
            "current heroes",
            "current hostage",
            "current hostages",
            "current level",
            "current mission",
            "current object",
            "current objective",
            "current objects",
            "current phase",
            "current player",
            "current players",
            "current round",
            "current target",
            "current targets",
            "current upgrade",
            "damage",
            "damaged",
            "damaging",
            "danger",
            "dead",
            "deal",
            "dealing",
            "dealt",
            "deck",
            "decks",
            "defeat",
            "defend",
            "defended",
            "defending",
            "defence",
            "deliver",
            "delivered",
            "delivering",
            "depth",
            "destabilize",
            "destabilized",
            "destabilizing",
            "destroy",
            "destroyed",
            "destroying",
            "detect",
            "detected",
            "detecting",
            "dexterity",
            "diamond",
            "diamonds",
            "die",
            "discard",
            "discarded",
            "discarding",
            "disconnect",
            "disconnected",
            "disconnecting",
            "distance",
            "distances",
            "dodge",
            "dodged",
            "dodging",
            "dome",
            "domes",
            "down",
            "download",
            "downloaded",
            "downloading",
            "draw",
            "drawing",
            "drawn",
            "drop",
            "dropped",
            "dropping",
            "dying",
            "east",
            "eliminate",
            "eliminated",
            "eliminating",
            "elimination",
            "eliminations",
            "enemies",
            "enemy",
            "entrance",
            "escort",
            "escorted",
            "escorting",
            "excellent",
            "exit",
            "experience",
            "extreme",
            "face",
            "faces",
            "facing",
            "failed",
            "failing",
            "failure",
            "fall",
            "fallen",
            "falling",
            "far",
            "fast",
            "faster",
            "fastest",
            "fault",
            "faults",
            "final",
            "final allies",
            "final ally",
            "final attempt",
            "final checkpoint",
            "final enemies",
            "final enemy",
            "final form",
            "final game",
            "final hero",
            "final heroes",
            "final hostage",
            "final hostages",
            "final item",
            "final level",
            "final mission",
            "final object",
            "final objective",
            "final objects",
            "final phase",
            "final player",
            "final players",
            "final round",
            "final target",
            "final targets",
            "final time",
            "final upgrade",
            "find",
            "finding",
            "finish",
            "finished",
            "finishing",
            "flown",
            "fly",
            "flying",
            "fold",
            "folded",
            "folding",
            "form",
            "forms",
            "forward",
            "found",
            "freeze",
            "freezing",
            "frozen",
            "game",
            "games",
            "games lost",
            "games won",
            "gg",
            "go",
            "goal",
            "goals",
            "going",
            "good",
            "good luck",
            "goodbye",
            "green",
            "guilty",
            "hack",
            "hacked",
            "hacking",
            "hand",
            "hands",
            "heal",
            "healed",
            "healer",
            "healers",
            "healing",
            "heart",
            "hearts",
            "height",
            "hello",
            "help",
            "here",
            "hero",
            "heroes",
            "hidden",
            "hide",
            "hiding",
            "high score",
            "high scores",
            "hit",
            "hitting",
            "hmmm",
            "hostage",
            "hostages",
            "huh",
            "hunt",
            "hunted",
            "hunter",
            "hunters",
            "hunting",
            "i give up",
            "i tried",
            "in view",
            "income",
            "incoming",
            "initial",
            "initial allies",
            "initial ally",
            "initial attempt",
            "initial checkpoint",
            "initial enemies",
            "initial enemy",
            "initial form",
            "initial game",
            "initial hero",
            "initial heroes",
            "initial hostage",
            "initial level",
            "initial mission",
            "initial object",
            "initial objective",
            "initial objects",
            "initial phase",
            "initial player",
            "initial players",
            "initial round",
            "initial target",
            "initial targets",
            "initial upgrade",
            "innocent",
            "inside",
            "intelligence",
            "interact",
            "invisible",
            "item",
            "items",
            "join",
            "joined",
            "joining",
            "jump",
            "jumping",
            "kill",
            "kills",
            "killstreak",
            "killstreak",
            "killstreaks",
            "leader",
            "leaders",
            "least",
            "left",
            "less",
            "level",
            "level down",
            "level up",
            "levels",
            "life",
            "limited",
            "lives",
            "load",
            "loaded",
            "loading",
            "location",
            "lock",
            "locked",
            "locking",
            "loser",
            "losers",
            "loss",
            "losses",
            "max",
            "mild",
            "min",
            "mission",
            "mission", /* what? */
            "mission aborted",
            "mission accomplished",
            "mission failed",
            "missions",
            "moderate",
            "money",
            "monster",
            "monsters",
            "more",
            "most",
            "my mistake",
            "near",
            "new high score",
            "new record",
            "next",
            "next allies",
            "next ally",
            "next attempt",
            "next checkpoint",
            "next enemies",
            "next enemy",
            "next form",
            "next game",
            "next hero",
            "next heroes",
            "next hostage",
            "next hostages",
            "next level",
            "next mission",
            "next object",
            "next objective",
            "next objects",
            "next phase",
            "next player",
            "next players",
            "next round",
            "next target",
            "next targets",
            "next upgrade",
            "nice try",
            "no",
            "no thanks",
            "none",
            "normal",
            "north",
            "northeast",
            "northwest",
            "not today",
            "object",
            "objective",
            "objectives",
            "objects",
            "obtain",
            "obtained",
            "obtaining",
            "off",
            "on",
            "oof",
            "oops",
            "optimal",
            "optimize",
            "optimized",
            "optimizing",
            "out of view",
            "outgoing",
            "outside",
            "over",
            "overtime",
            "participant",
            "participants",
            "payload",
            "payloads",
            "phase",
            "phases",
            "pick",
            "picked",
            "picking",
            "pile",
            "piles",
            "play",
            "played",
            "player",
            "players",
            "playing",
            "point",
            "points",
            "points earned",
            "points lost",
            "position",
            "power",
            "power-up",
            "power-ups",
            "price",
            "primary fire",
            "projectile",
            "projectiles",
            "protect",
            "protected",
            "protecting",
            "purified",
            "purify",
            "purifying",
            "purple",
            "raise",
            "raised",
            "raising",
            "rank",
            "rank a",
            "rank b",
            "rank c",
            "rank d",
            "rank e",
            "rank f",
            "rank s",
            "reach",
            "reached",
            "reaching",
            "ready",
            "record",
            "records",
            "recover",
            "recovered",
            "recovering",
            "red",
            "remain",
            "remaining",
            "rescue",
            "rescued",
            "rescuing",
            "resource",
            "resources",
            "resurrect",
            "resurrected",
            "resurrecting",
            "reveal",
            "revealed",
            "revealing",
            "right",
            "round",
            "round {0}",
            "rounds",
            "rounds lost",
            "rounds won",
            "run",
            "running",
            "safe",
            "save",
            "saved",
            "saving",
            "score",
            "scores",
            "secondary fire",
            "secure",
            "secured",
            "securing",
            "select",
            "selected",
            "selecting",
            "sell",
            "selling",
            "server load",
            "server load average",
            "server load peak",
            "sever",
            "severe",
            "severed",
            "severing",
            "shop",
            "shops",
            "shuffle",
            "shuffled",
            "sink",
            "sinking",
            "skip",
            "skipped",
            "skipping",
            "sleep",
            "sleeping",
            "slept",
            "slow",
            "slower",
            "slowest",
            "sold",
            "sorry",
            "south",
            "southeast",
            "southwest",
            "spade",
            "spades",
            "sparkles",
            "spawn",
            "spawned",
            "spawning",
            "speed",
            "speeds",
            "sphere",
            "spheres",
            "stabilize",
            "stabilized",
            "stabilizing",
            "stable",
            "star",
            "stars",
            "start",
            "started",
            "starting",
            "status",
            "stay",
            "stay away",
            "stayed",
            "staying",
            "stop",
            "stopped",
            "stopping",
            "strength",
            "stun",
            "stunned",
            "stunning",
            "suboptimal",
            "success",
            "sudden death",
            "sunk",
            "superb",
            "survive",
            "survived",
            "surviving",
            "target",
            "targets",
            "team",
            "teammate",
            "teammates",
            "teams",
            "terrible",
            "thank you",
            "thanks",
            "that was awesome",
            "threat",
            "threat level",
            "threat levels",
            "threats",
            "tiebreaker",
            "time",
            "times",
            "total",
            "trade",
            "traded",
            "trading",
            "traitor",
            "traitors",
            "transfer",
            "transferred",
            "transferring",
            "try again",
            "turret",
            "turrets",
            "ugh",
            "ultimate ability",
            "under",
            "unknown",
            "unlimited",
            "unlock",
            "unlocked",
            "unlocking",
            "unsafe",
            "unstable",
            "up",
            "upgrade",
            "upgrades",
            "upload",
            "uploaded",
            "uploading",
            "use ability 1",
            "use ability 2",
            "use ultimate ability",
            "victory",
            "visible",
            "vortex",
            "vortices",
            "wait",
            "waiting",
            "wall",
            "walls",
            "warning",
            "welcome",
            "well played",
            "west",
            "white",
            "wild",
            "win",
            "winner",
            "winners",
            "wins",
            "wisdom",
            "worse",
            "worst",
            "wow",
            "yellow",
            "yes",
            "you",
            "you lose",
            "you win",
            "zone",
            "zones",
            "¡{0}!",
            "¿{0}?"
        };

        public static readonly string[] AllOperations = { 
            "^", "*", "%", "/", "+", "-", 
            "<", "<=", "==", ">=", ">", "!=",
            "&", "|" 
        };
        public static readonly string[] MathOperations = new string[] { "^", "*", "%", "/", "+", "-" };
        public static readonly string[] CompareOperations = new string[] { "<", "<=", "==", ">=", ">", "!=" };
        public static readonly string[] BoolOperations = new string[] { "&", "|" };
    }
}
